### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by 0xExpensive** [ashanahw/VirusTotal-Hash-Converter#1]
W:\>cd hash

W:\hash>python VTC.py hash
Traceback (most recent call last):
  File "W:\hash\VTC.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

done with an excel file with a md5 hash in the first column (has results on vt)
python 3.9.1
tried running the command with the inputfile extension in the name as well (.xlsl), tried running as admin and not as admin

**Comment by ashanahw** [comment]
install the required modules using pip command in console
 eg; pip install requests
